version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql		
    healthcheck:
               test: ["CMD", "mysql", "-u", "root", "-padmin", "-e", "SELECT 1"]
               interval: 5s
               timeout: 5s
               retries: 10
               start_period: 60s

    networks:
      - two-tier-net

  flask:
    image: two-tier-backend:latest
    container_name: flask-app
    ports:
    - "5005:5000"
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: admin
       MYSQL_DB: mydb
    depends_on:
       mysql:
          condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
   
    networks:
      - two-tier-net
networks:
  two-tier-net:

volumes:
  mysql-data:
